import { Format, Persona, Framework, Producer } from './types';

export const FORMATS: { name: Format; tracks: number; description: string }[] = [
  { name: 'Single Track', tracks: 1, description: '1 song' },
  { name: 'Freestyle', tracks: 1, description: '1 song, 32 bars (no hook)' },
  { name: 'EP', tracks: 6, description: '6 tracks' },
  { name: 'Mixtape', tracks: 20, description: '20 tracks' },
  { name: 'Album', tracks: 13, description: '13 tracks' },
];

export const LOCKED_PERSONAS: Persona[] = [
  {
    id: 'adrian',
    name: 'ADRIAN',
    isCustom: false,
    vocalBlock: 'male rapper, King Los vocal style, mid-to-high tenor register, razor sharp diction, elite syllable precision, chopper flow with melodic switches, Baltimore grit meets polished delivery, breathtaking breath control, technical lyricism with emotional depth, multisyllabic rhyme schemes',
  },
  {
    id: 'dray',
    name: 'DRAY',
    isCustom: false,
    vocalBlock: 'male R&B vocalist, Usher vocal style, smooth mid-low tenor, warm laid-back melodic delivery, breathy on intimate lines, controlled falsetto on emotional peaks, Usher influence only, disciple energy not imitation',
  },
  {
    id: 'king-fable',
    name: 'KING FABLE',
    isCustom: false,
    vocalBlock: 'male rapper, deep baritone, smooth with weight, controlled authoritative delivery, cinematic storytelling rap, Nas and Big Pun influence, precise diction, mid-low pitch with gravity and presence',
  },
  {
    id: 'sage',
    name: 'SAGE',
    isCustom: false,
    vocalBlock: 'female R&B vocalist, Jhene Aiko vocal style, soft breathy soprano, meditative and emotionally intimate delivery, smooth conversational phrasing with melodic undertones, warm vulnerability, airy tone with quiet power underneath, harmonic layering on emotional peaks, whisper to full voice dynamic range',
  },
  {
    id: 'glider',
    name: 'GLIDER',
    isCustom: false,
    vocalBlock: 'Male bright agile tenor, smooth melisma, precise vocal runs, seamless falsetto transitions, controlled breath, rhythmic phrasing',
  },
  {
    id: 'street-narrator',
    name: 'STREET NARRATOR',
    isCustom: false,
    vocalBlock: 'Male deep baritone crooner, talk-singing delivery, flat pitch tone, laid-back drawl, minimal movement, smooth low-end presence',
  },
  {
    id: 'global-icon',
    name: 'GLOBAL ICON',
    isCustom: false,
    vocalBlock: 'Male high energetic tenor, sharp staccato delivery, rhythmic vocal ticks, breathy attacks, percussive phrasing, dynamic intensity',
  },
  {
    id: 'soul-warrior',
    name: 'SOUL WARRIOR',
    isCustom: false,
    vocalBlock: 'Female gritty mezzo-soprano, raw emotional delivery, strained tone, slight rasp, expressive imperfections, powerful feeling',
  },
  {
    id: 'conscious-queen',
    name: 'CONSCIOUS QUEEN',
    isCustom: false,
    vocalBlock: 'Female warm raspy alto, rap-singing blend, conversational phrasing, soulful runs, rhythmic speech melody, expressive tone',
  },
  {
    id: 'whistle-queen',
    name: 'WHISTLE QUEEN',
    isCustom: false,
    vocalBlock: 'Female wide-range soprano, whistle register, airy tone, powerful belting, intricate runs, extreme vocal control',
  },
  {
    id: 'silky-soul',
    name: 'SILKY SOUL',
    isCustom: false,
    vocalBlock: 'Male smooth intimate tenor, soft delivery, layered vocals, gentle falsetto, warm tone, subtle phrasing',
  },
  {
    id: 'memphis-high',
    name: 'MEMPHIS HIGH',
    isCustom: false,
    vocalBlock: 'Male high falsetto tenor, soft attack, airy tone, emotional squeals, expressive head voice, delicate delivery',
  },
  {
    id: 'warm-baritone',
    name: 'WARM BARITONE',
    isCustom: false,
    vocalBlock: 'Male deep rich baritone, gospel-influenced runs, warm tone, clear diction, emotional weight, controlled power',
  },
  {
    id: 'velvet-smooth',
    name: 'VELVET SMOOTH',
    isCustom: false,
    vocalBlock: 'Male polished velvet tenor, smooth sustained notes, seamless phrasing, controlled breath, rich tone, elegant delivery',
  },
  {
    id: 'neo-soul-vibe',
    name: 'NEO-SOUL VIBE',
    isCustom: false,
    vocalBlock: 'Male smoky relaxed tenor, mumbling delivery, behind-the-beat phrasing, loose timing, falsetto layering, groove-heavy tone',
  },
  {
    id: 'deep-crooner',
    name: 'DEEP CROONER',
    isCustom: false,
    vocalBlock: 'Male heavy resonant baritone, strong chest voice, emotional belting, raw intensity, powerful projection, strained delivery',
  },
  {
    id: 'rhythm-pony',
    name: 'RHYTHM PONY',
    isCustom: false,
    vocalBlock: 'Male breathy rhythmic tenor, staccato phrasing, audible breathing, syncopated delivery, sharp vocal hits, playful tone',
  },
  {
    id: 'retro-funk',
    name: 'RETRO FUNK',
    isCustom: false,
    vocalBlock: 'Male raspy energetic tenor, gritty vocal fry, dynamic range shifts, falsetto bursts, expressive ad-libs, vintage tone',
  },
  {
    id: 'southern-grit',
    name: 'SOUTHERN GRIT',
    isCustom: false,
    vocalBlock: 'Male textured raspy baritone, gritty tone, slurred phrasing, soulful shouting, vocal fry, emotional depth',
  },
  {
    id: 'diva',
    name: 'DIVA',
    isCustom: false,
    vocalBlock: 'Female powerful soprano, clean tone, strong vibrato, full belting, precise control, crystal clarity',
  },
  {
    id: 'soul-queen',
    name: 'SOUL QUEEN',
    isCustom: false,
    vocalBlock: 'Female commanding alto, gospel runs, strong vibrato, call-and-response phrasing, powerful projection, soulful grit',
  },
  {
    id: 'growler',
    name: 'GROWLER',
    isCustom: false,
    vocalBlock: 'Female aggressive agile soprano, vocal growls, complex runs, dynamic control, powerful belting, edgy tone',
  },
  {
    id: 'piano-soul',
    name: 'PIANO SOUL',
    isCustom: false,
    vocalBlock: 'Female husky mezzo-soprano, raw tone, emotional cracks, strained belting, natural phrasing, expressive delivery',
  },
  {
    id: 'island-pop',
    name: 'ISLAND POP',
    isCustom: false,
    vocalBlock: 'Female nasal mezzo tone, minimal delivery, monotone phrasing, vocal fry, accented vowels, cool detached style',
  },
  {
    id: 'ethereal-vibe',
    name: 'ETHEREAL VIBE',
    isCustom: false,
    vocalBlock: 'Female soft light soprano, airy tone, slurred phrasing, conversational flow, gentle falsetto, loose articulation',
  },
  {
    id: 'soft-touch',
    name: 'SOFT TOUCH',
    isCustom: false,
    vocalBlock: 'Female breathy soft soprano, whisper-singing, smooth legato, light tone, minimal delivery, airy texture',
  },
  {
    id: 'vocal-bible',
    name: 'VOCAL BIBLE',
    isCustom: false,
    vocalBlock: 'Female low textured mezzo, stacked harmonies, intricate runs, layered vocals, precise control, rich tone',
  },
  {
    id: 'sweetheart',
    name: 'SWEETHEART',
    isCustom: false,
    vocalBlock: 'Female light airy soprano, soft delivery, simple melodies, breathy tone, smooth phrasing, gentle expression',
  },
  {
    id: 'church-belter',
    name: 'CHURCH BELTER',
    isCustom: false,
    vocalBlock: 'Female powerhouse alto, explosive belting, gospel runs, sustained notes, dramatic projection, intense delivery',
  },
  {
    id: 'street-scholar',
    name: 'STREET SCHOLAR',
    isCustom: false,
    vocalBlock: 'Male raspy baritone, authoritative tone, multi-syllabic rhymes, behind-the-beat flow, spoken-word cadence, lyrical storytelling, calm but intense delivery',
  },
  {
    id: 'liquid-legend',
    name: 'LIQUID LEGEND',
    isCustom: false,
    vocalBlock: 'Male smooth melodic tenor, rapid triplet flow, sing-rap cadence, self-harmonized vocals, fluid phrasing, fast but controlled delivery',
  },
  {
    id: 'lyrical-juggernaut',
    name: 'LYRICAL JUGGERNAUT',
    isCustom: false,
    vocalBlock: 'Male booming clear voice, extreme breath control, rapid-fire delivery, heavy alliteration, aggressive articulation, dense rhythmic phrasing',
  },
  {
    id: 'vocal-shapeshifter',
    name: 'VOCAL SHAPESHIFTER',
    isCustom: false,
    vocalBlock: 'Male dynamic vocal range, pitch-shifting delivery, emotional bursts, theatrical expression, erratic cadence changes, high intensity storytelling',
  },
  {
    id: 'pattern-master',
    name: 'PATTERN MASTER',
    isCustom: false,
    vocalBlock: 'Male sharp precise tenor, machine-gun delivery, compound rhymes, ultra-clear diction, rapid technical flow, punchy cadence control',
  },
  {
    id: 'abstract-professor',
    name: 'ABSTRACT PROFESSOR',
    isCustom: false,
    vocalBlock: 'Male intellectual nasal tone, dense lyrical phrasing, metaphor-heavy delivery, spoken-word influence, controlled cadence, layered meaning',
  },
  {
    id: 'relatable-king',
    name: 'RELATABLE KING',
    isCustom: false,
    vocalBlock: 'Male warm conversational baritone, smooth storytelling flow, relaxed cadence, subtle melodic tone, natural speech rhythm, introspective delivery',
  },
  {
    id: 'poetic-go-go',
    name: 'POETIC GO-GO',
    isCustom: false,
    vocalBlock: 'Male expressive dynamic tenor, spoken-word cadence, rhythmic swing, poetic phrasing, emotional articulation, off-grid bounce',
  },
  {
    id: 'platinum-player',
    name: 'PLATINUM PLAYER',
    isCustom: false,
    vocalBlock: 'Male confident clear tenor, bouncy flow, pocket-focused delivery, conversational cadence, punchy rhythm control, smooth swagger',
  },
  {
    id: 'martian',
    name: 'MARTIAN',
    isCustom: false,
    vocalBlock: 'Male high raspy nasal tone, vocal fry texture, slurred melodic phrasing, free-associative flow, unpredictable cadence, playful chaotic delivery',
  },
  {
    id: 'smooth-operator',
    name: 'SMOOTH OPERATOR',
    isCustom: false,
    vocalBlock: 'Male silky relaxed tenor, behind-the-beat delivery, laid-back cadence, smooth melodic phrasing, effortless cool tone, slow drag flow',
  },
  {
    id: 'chameleon',
    name: 'CHAMELEON',
    isCustom: false,
    vocalBlock: 'Male smooth agile tenor, sing-rap hybrid delivery, rapid triplet flow, melodic phrasing, seamless switches between singing and rapping, vowel elongation, harmonized layers, dynamic cadence shifts',
  }
];

export const FRAMEWORKS: Framework[] = [
  { id: '1', name: 'Smooth Storytelling', description: 'Nas, Jay-Z, Biggie lane.', cadence: 'straight time flow, pocket cadence, conversational delivery' },
  { id: '2', name: 'Smooth to Melodic', description: 'Usher, Lauryn Hill, Nate Dogg lane.', cadence: 'laid-back melodic flow, bounce and stretch cadence, harmonic layers on hooks' },
  { id: '3', name: 'Aggression', description: 'DMX, 50 Cent, Onyx lane.', cadence: 'push flow, stop-start cadence, chant energy, aggressive projection' },
  { id: '4', name: 'Speed', description: 'Bone Thugs, Twista, Eminem lane.', cadence: 'triplet flow, run-on phrasing, double-time bursts, breathless momentum' },
  { id: '5', name: 'Groove and Bounce', description: 'Biggie, Missy Elliott, Q-Tip lane.', cadence: 'pocket flow, syncopated cadence, bounce and stretch, groove-locked' },
  { id: '6', name: 'Controlled Chaos', description: 'Andre 3000, ODB, Busta Rhymes lane.', cadence: 'off-grid flow, accent switch cadence, stop-start, unpredictable and intentional' },
  { id: '7', name: 'Hybrid Classic', description: 'Nas, Drake, Jay-Z lane.', cadence: 'straight time home base, one major double-time switch, hybrid cadence, cinematic arc' },
];

export const PRODUCERS: Producer[] = [
  { id: 'j-soul', name: 'J Soul', tags: '90s Boom Bap, DJ Scratching, Jazz Samples, Dusty Lo-Fi Texture' },
  { id: 'marcus-sterling', name: 'Marcus Sterling', tags: 'Chipmunk Soul Sample, Luxury Trap, Heavy 808s' },
  { id: 'london-on-da-track', name: 'London on da Track', tags: 'Melodic Trap, Piano Lead, Rolling 808s' },
  { id: 'soul-preme', name: 'Soul-Preme', tags: 'Early 2000s Hip Hop, High Pitch Vocal Sample, MPC 3000 Swing' },
  { id: 'the-prophet', name: 'The Prophet', tags: 'Midwest Melodic Rap, Gospel, Choir Harmonies, Church Organ' },
  { id: 'the-maestr-o', name: 'The Maestr-O', tags: 'Cinematic Orchestral, Dramatic Violins, Cello Staccato' },
  { id: 'alchemist-of-ache', name: 'Alchemist of Ache', tags: '90s R&B, Gritty Boom Bap, Fender Rhodes, Deep Sub Bass' },
  { id: 'groove-architect', name: 'Groove Architect', tags: 'Deep House, Neo-Soul, Funk, Dilla Swing, Bouncy' },
  { id: 'velvet-grinder', name: 'Velvet Grinder', tags: '90s Midwest G-Funk, Melodic Hip-Hop, Deep Rolling Bass' },
  { id: 'quincy-jones', name: 'Quincy Jones', tags: 'Jazz-Fusion, Complex Arrangements, Cinematic Orchestral' },
  { id: 'babyface', name: 'Babyface', tags: 'Velvet textures, Romantic R&B, Acoustic Guitar, Smooth Synths' },
  { id: 'teddy-riley', name: 'Teddy Riley', tags: 'New Jack Swing, Hard Hitting Drums, Orchestra Hits' },
  { id: 'dr-dre', name: 'Dr. Dre', tags: 'West Coast, Clean Mixing, High-pitched Sine Whistles, P-Funk Bass' },
  { id: 'dj-quik', name: 'DJ Quik', tags: 'Funky, Jazzy, Talkbox, Handclaps, Groovy Bass' },
  { id: 'noah-40-shebib', name: 'Noah “40” Shebib', tags: 'ambient pop-R&B, underwater filter, low-pass textures, moody pads, sparse drums, muted kicks, soft rimshots, sub bass, emotional space, wide stereo reverb, melancholic tone' },
  { id: 'boi-1da', name: 'Boi-1da', tags: 'trap, dancehall fusion, hard kicks, crisp snares, aggressive 808s, brass stabs, chant energy, stadium bounce, high energy, anthemic feel' },
  { id: 'dmile', name: 'D’Mile', tags: 'retro soul R&B, live bass, analog warmth, vintage keys, tape saturation, subtle swing, rich chords, modern clean mix, organic instrumentation' },
  { id: 'dj-mustard', name: 'DJ Mustard', tags: 'minimalist west coast, simple basslines, clap-driven drums, sparse melodies, repetitive hooks, club bounce, dry mix, infectious groove' },
  { id: 'metro-boomin', name: 'Metro Boomin', tags: 'dark trap, cinematic atmosphere, minor key melodies, eerie bells, deep 808s, heavy kicks, dramatic builds, haunting pads, aggressive tone' },
  { id: 'timbaland', name: 'Timbaland', tags: 'futuristic R&B, beatbox percussion, stutter effects, syncopated drums, experimental rhythms, digital textures, unconventional bounce' },
  { id: 'darkchild', name: 'Darkchild (Rodney Jerkins)', tags: 'Y2K pop-R&B, polished drums, vocal chops, glossy synths, tight groove, layered harmonies, clean commercial mix' },
  { id: 'jermaine-dupri', name: 'Jermaine Dupri', tags: 'Atlanta bass, uptempo bounce, party drums, playful synths, call-and-response hooks, high energy groove' },
  { id: 'velvet-vic', name: 'Velvet Vic', tags: 'late night R&B, smooth jazz chords, electric piano, slow tempo, warm basslines, lush pads, key modulation, intimate mix' },
  { id: 'the-headliner', name: 'The Headliner', tags: 'pop-rap, pop-R&B, bright synths, catchy chord progressions, punchy drums, hook-driven structure, upbeat energy, radio-ready mix' },
  { id: 'the-crossover', name: 'The Crossover', tags: 'hip-hop/R&B blend, hard drum verses, soft melodic choruses, layered vocals, dynamic contrast, emotional hooks, commercial structure' },
  { id: 'the-idol', name: 'The Idol', tags: 'pop-R&B, dance-pop energy, glossy synth layers, smooth chord progressions, clean drums, warm basslines, lush vocal space, high fidelity mix, commercial polish, emotional clarity' },
  { id: 'the-broadway-director', name: 'The Broadway Director', tags: 'orchestral pop, piano-driven melodies, lush strings, theatrical builds, vocal-forward mix, key changes, dramatic transitions, emotional chord progressions, high fidelity, Broadway storytelling' },
  { id: 'the-island-composer', name: 'The Island Composer', tags: 'Latin and Caribbean fusion, acoustic percussion, nylon guitar, rhythmic bounce, warm basslines, syncopated drums, group vocals, organic instrumentation, uplifting tone' },
  { id: 'the-epic-composer', name: 'The Epic Composer', tags: 'cinematic orchestral, choir vocals, tribal percussion, sweeping strings, deep drums, dramatic builds, powerful drops, wide stereo, heroic tone' },
  { id: 'the-pen-griffey', name: 'The Pen Griffey (TrapSoul)', tags: 'trap soul, slow tempo, reverb-heavy vocals, emotional pads, deep 808s, minimal drums, chopped R&B samples, melancholic tone' },
  { id: 'the-boom', name: 'The Boom', tags: 'trap soul boom bap, vintage soul samples, deep 808 bass, dusty drums, heavy kicks, emotional grit, modern bounce' },
  { id: 'the-don', name: 'The Don', tags: 'mafioso rap, fast boom bap drums, 70s funk samples, aggressive loops, cinematic tension, gritty texture' },
  { id: 'the-concrete-conguero', name: 'The Concrete Conguero', tags: 'tribal hip-hop, rolling congas, live percussion, breakbeats, upright bass, rhythmic layering, organic groove' },
  { id: 'the-delta-drifter', name: 'The Delta Drifter', tags: 'blues rap, clean electric guitar, rimshot drums, minimal percussion, no hi-hats, empty space, raw emotion' },
  { id: 'the-calle-flow', name: 'The Calle Flow', tags: 'latin trap, reggaeton bounce, dembow rhythm, nylon guitar, sharp hi-hats, club energy, melodic hooks' },
  { id: 'the-concrete-conductor', name: 'The Concrete Conductor', tags: 'cinematic hip-hop, opera samples, orchestral layers, dark choir, heavy boom bap drums, dramatic builds, apocalyptic tone' },
  { id: 'the-havana-maestro', name: 'The Havana Maestro', tags: 'Cuban salsa fusion, piano montuno, clave rhythm, live brass, congas, syncopated basslines, high energy groove' }
];
